### ISSUE TITLE
Error: spawn ENOMEM

### ISSUE THREAD

**Issue by ZhongxuYang** [ZhongxuYang/vite-plugin-version-mark#3]
```sh
error during build:
Error: spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:700:9)
    at Object.execFile (node:child_process:327:17)
    at exec (node:child_process:225:25)
    at /repo/node_modules/vite-plugin-version-mark/dist/vite/index.cjs:39:5
    at new Promise (<anonymous>)
    at getGitSHA (/repo/node_modules/vite-plugin-version-mark/dist/vite/index.cjs:38:10)
    at analyticOptions (/repo/node_modules/vite-plugin-version-mark/dist/vite/index.cjs:59:41)
    at transformIndexHtml (/repo/node_modules/vite-plugin-version-mark/dist/vite/index.cjs:84:17)
    at applyHtmlTransforms (file:///repo/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:37952:27)
    at async Object.generateBundle (file:///repo/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:37823:26)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Build step 'Execute shell' marked build as failure
New run name is '#229-haida-webapp-2nd'
Finished: FAILURE
```

**Comment by ZhongxuYang** [comment]
[same issue](https://github.com/facebook/create-react-app/issues/12465)

Look like need Uninstalled antivirus.
